# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01fa1acdaeec3f3392ed84e9ebd9bf8be3734579d8c5be332928af85a95d752e09eb9efa3fdc511e0cfbd25dd92204d5f42534e9c417060546941d1bed345155

test:
  secret_key_base: 7d093c0dacd44a6e04a4beeb4643b117f8e01c5ab78678871fd32d93d557e6c94f1f6a9aeaf409864509e2f1707c9e32743e21982b85b0397a5f7fdd6ce42287

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
